[project]
name = "makemore"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "ipykernel",
    "matplotlib>=3.10.7",
    "numpy>=2.2.6",
    "torch>=2.9.1",
]
